name: asset_scanner
description: "สแกน QR ทรัพย์สิน คู่กับระบบ asset-laravel"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  mobile_scanner: ^7.4.2
  shared_preferences: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
